MVCBlog/MVCBlog/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using EntitiyLayer.Concrete;

namespace MVCBlog.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        AboutManager abm = new AboutManager();
        public ActionResult Index()
        {
            var aboutcontent= abm.GetAll();
            return View(aboutcontent);
        }

        public PartialViewResult Footer()

        {
            

           var aboutcontentlist= abm.GetAll();
            return PartialView(aboutcontentlist);
        }

        public PartialViewResult MeetTheTeam()
        {
            AuthorManager authorman = new AuthorManager();
            var authorlist = authorman.GetAll();
            return PartialView(authorlist);
        }

        [HttpGet]
        public ActionResult UpdateAboutList()
        {
            var aboutlist= abm.GetAll();
            return View(aboutlist);
        }

        [HttpPost]
        public ActionResult UpdateAbout(About p)
        {
           abm.UpdateAboutBm(p);
            return RedirectToAction("UpdateAboutList");
        }

    }
}

MVCBlog/MVCBlog/Controllers/MailSubscribeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using EntitiyLayer.Concrete;

namespace MVCBlog.Controllers
{
    public class MailSubscribeController : Controller
    {
        [HttpGet]
        public PartialViewResult AddMail()
        {
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult AddMail(SubscribeMail p)
        {
            SubscribeMailManager sm= new SubscribeMailManager();
            sm.BLAdd(p);
            return PartialView( );
        }
    }
}

MVCBlog/MVCBlog/Views/About/Footer.cshtml
@model IEnumerable<EntitiyLayer.Concrete.About>

<div class="site-footer">
    <div class="container">
        <div class="row mb-5">
            @foreach(var x in Model)
            {
            <div class="col-md-4">
                <h3 class="footer-heading mb-4">Hakkımızda</h3>
                <p>@x.AboutConcat1</p>
            </div>
            }
            <div class="col-md-3 ml-auto">
                <!-- <h3 class="footer-heading mb-4">Navigation</h3> -->
                <ul class="list-unstyled float-left mr-5">
                    <li><a href="/About/Index">Hakkımızda</a></li>
                    <li><a href="/Concat/SendMessage">İletişim</a></li>
                    <li><a href="/Blog/Index">Ana Sayfa</a></li>
                    <li><a href="/Author/Login">Yazar Girişi</a></li>
                </ul>
                <ul class="list-unstyled float-left">
                    <li><a href="/Blog/BlogByCategory/8/">Seyhat</a></li>
                    <li><a href="/Blog/BlogByCategory/1/">Yazılım</a></li>
                    <li><a href="/Blog/BlogByCategory/3/">Film & Dizi</a></li>
                    <li><a href="/Blog/BlogByCategory/2/">Teknoloji</a></li>
                </ul>
            </div>
            <div class="col-md-4">


                <div>
                    <h3 class="footer-heading mb-4">Sosyal Medya Hesaplarımız</h3>
                    <p>
                        <a href="#"><span class="icon-facebook pt-2 pr-2 pb-2 pl-0"></span></a>
                        <a href="#"><span class="icon-twitter p-2"></span></a>
                        <a href="#"><span class="icon-instagram p-2"></span></a>
                        <a href="#"><span class="icon-rss p-2"></span></a>
                        <a href="#"><span class="icon-envelope p-2"></span></a>
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-center">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> | TRMN Dijital © 2023 | Tüm Hakları Saklıdır <br /> <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</div>

MVCBlog/MVCBlog/Views/About/Index.cshtml
@model IEnumerable<EntitiyLayer.Concrete.About>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}



<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('/miniblog/images/img_4.jpg');">
    <div class="container">
        <div class="row same-height justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
                    <h1 class="">Hakkımızda</h1>
                    <p class="lead mb-4 text-white"> Yazarlarımızı Tanıyın</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">

            <div class="col-md-6 order-md-2">
                @foreach (var item in Model)
                {
                    <img src="@item.AboutImage1" alt="Image" class="img-fluid">

                }
            </div>
            <div class="col-md-5 mr-auto order-md-1">
                <h2>Biz kimiz?</h2>

                @foreach (var item in Model)
                {

                    <p>@item.AboutConcat1</p>
                }
                <ul class="ul-check list-unstyled success">
                    <li>Her Gün Onlarca Blog Yazısı</li>
                    <li>15' den fazla kategori</li>
                    <li>Günlük 45000+ tekil okumali</li>
                    <li>Yazarlarımızın ortalama 5 yıllık tecrübesi</li>
                    <li>Sosyal Medyalarda 35000+ Üzeri Takipçi</li>

                </ul>
            </div>

        </div>
    </div>
</div>
@Html.Action("MeetTheTeam", "About")


<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                @foreach (var item in Model)
                {
                    <img src="@item.AboutImage2" alt="Image" class="img-fluid">
                }
            </div>
            <div class="col-md-5 ml-auto">
                <h2>Neler Yapıyoruz</h2>
                <p class="mb-4">
                    @foreach (var item in Model)
                    {
                        @item.AboutConcat2
                    }
                </p>

                <ul class="ul-check list-unstyled success">
                    <li>Film ve Dizi Yorumları</li>
                    <li>Dünyanın Bir Çok Yerinden Yazılar</li>
                    <li>Son Gelişmiş Teknoloji Haberleri</li>
                    <li>Yeni Çıkan Oyunlar ve İncelemeleri</li>
                    <li>Yeni Çıkan Kitaplar ve İncelemeleri</li>
                    <li>Yeni Çıkan Albümler ve İncelemeleri</li>
                </ul>
            </div>
        </div>
    </div>
</div>

@Html.Action("AddMail", "MailSubscribe")


@Html.Action("Footer", "About")

MVCBlog/MVCBlog/Views/About/MeetTheTeam.cshtml
@model IEnumerable<EntitiyLayer.Concrete.Author>
<div class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-5 text-center">
                <h2>Yazar Ekibimiz</h2>
                <p>Sizlere birbirinden güzel içerikler sunan yazarlarımız. Siz de yazarımız olmak isterseniz bizimle iletişime geçebilirsiniz</p>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-6 col-lg-4 mb-5 text-center">
                    <img src="@item.AuthorImage" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
                    <h2 class="mb-3 h5">@item.AuthorName</h2>
                    <p>@item.AuthorAbout</p>

                    <p class="mt-5">
                        <a href="#" class="p-3"><span class="icon-facebook"></span></a>
                        <a href="#" class="p-3"><span class="icon-instagram"></span></a>
                        <a href="#" class="p-3"><span class="icon-twitter"></span></a>
                    </p>
                </div>

            }
        </div>
    </div>
</div>

MVCBlog/MVCBlog/Views/About/UpdateAboutList.cshtml
@model IEnumerable<EntitiyLayer.Concrete.About>
@{
    ViewBag.Title = "UpdateAbout";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>UpdateAbout</h2>

<!DOCTYPE html>

<html>

<body class="hold-transition sidebar-mini">



    <!-- Main content -->

    <section class="content">

        <div class="row">

            <div class="col-md-12">

                <div class="card card-cyan">

                    <div class="card-header">

                        <h3 class="card-title">Hakkımızda Sayfa Düzenlemesi</h3>

                        <div class="card-tools">

                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                        </div>

                    </div>
                    @using (Html.BeginForm("UpdateAbout", "About", FormMethod.Post))
                    {
                        <div class="card-body">
                            @foreach (var item in Model)
                            {
                                <div class="form-group">

                                    <label for="inputName">İd</label>

                                    <input type="text" name="AboutId" class="form-control" value="@item.AboutId">

                                </div>
                                <div class="form-group">

                                    <label for="inputName">Görsel 1</label>

                                    <input type="text" name="AboutImage1" class="form-control" value="@item.AboutImage1">

                                </div>
                                <div class="form-group">

                                    <label for="inputName">Görsel 2</label>

                                    <input type="text" name="AboutImage2" class="form-control" value="@item.AboutImage2">

                                </div>

                                <div class="form-group">

                                    <label for="inputDescription">Açıklama 1</label>

                                    <textarea name="AboutConcat1" class="form-control" rows="4">@item.AboutConcat1</textarea>

                                </div>
                                <div class="form-group">

                                    <label for="inputDescription">Açıklama 2</label>

                                    <textarea name="AboutConcat2" class="form-control" rows="4">@item.AboutConcat2</textarea>

                                </div>


                            }

                            <button class="btn btn-info">Güncelle</button>
                            <a href="/About/Index" class="btn btn-secondary">Görüntüle</a>


                        </div>
                    }

                    <!-- /.card-body -->

                </div>



            </div>



        </div>



    </section>

</body>

</html>